// Generates js/levels.js: a fixed, ordered set of puzzles that ramp in difficulty.
// Usage: node tools/make-levels.mjs
// Deterministic (seeded), so re-running produces the same levels.
import { writeFileSync } from 'node:fs';

let seed = 20261006;
Math.random = () => {
  // mulberry32
  seed = (seed + 0x6d2b79f5) | 0;
  let t = seed;
  t = Math.imul(t ^ (t >>> 15), t | 1);
  t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
  return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
};

const { generate, PEERS, ROW, COL, BOX } = await import('../js/sudoku.js');

// Returns true if the puzzle can be finished using only naked and hidden singles.
function singlesOnly(puzzle) {
  const g = puzzle.slice();
  const units = [];
  for (let k = 0; k < 9; k++) {
    units.push([...Array(81).keys()].filter((i) => ROW[i] === k));
    units.push([...Array(81).keys()].filter((i) => COL[i] === k));
    units.push([...Array(81).keys()].filter((i) => BOX[i] === k));
  }
  const cands = (i) => {
    let m = 0x3fe;
    for (const p of PEERS[i]) if (g[p]) m &= ~(1 << g[p]);
    return m;
  };
  for (;;) {
    let progress = false;
    for (let i = 0; i < 81; i++) {
      if (g[i]) continue;
      const m = cands(i);
      if (m && !(m & (m - 1))) { g[i] = Math.log2(m); progress = true; }
    }
    for (const u of units) {
      for (let d = 1; d <= 9; d++) {
        if (u.some((i) => g[i] === d)) continue;
        const spots = u.filter((i) => !g[i] && cands(i) & (1 << d));
        if (spots.length === 1) { g[spots[0]] = d; progress = true; }
      }
    }
    if (g.every(Boolean)) return true;
    if (!progress) return false;
  }
}

// Each tier ramps from `from` clues down to `to` clues across its levels.
// Weighted toward the harder end: most levels are medium or above.
const TIERS = [
  { difficulty: 'easy', count: 20, from: 46, to: 41 },
  { difficulty: 'medium', count: 45, from: 40, to: 34 },
  { difficulty: 'hard', count: 45, from: 33, to: 29 },
  { difficulty: 'expert', count: 40, from: 28, to: 24 },
];

const levels = [];
for (const { difficulty, count, from, to } of TIERS) {
  for (let n = 0; n < count; n++) {
    const target = Math.round(from - (from - to) * (n / (count - 1)));
    for (;;) {
      const { puzzle } = generate(difficulty, target);
      const clues = puzzle.filter(Boolean).length;
      if (Math.abs(clues - target) > 1) continue;
      // Easy and medium levels must be solvable with simple logic (no guessing).
      if ((difficulty === 'easy' || difficulty === 'medium') && !singlesOnly(puzzle)) continue;
      levels.push({ d: difficulty, p: puzzle.join('') });
      break;
    }
  }
}

const body = levels.map((l) => `  ['${l.d}', '${l.p}'],`).join('\n');
writeFileSync(
  new URL('../js/levels.js', import.meta.url),
  `// Generated by tools/make-levels.mjs — do not edit by hand.\n// Each entry: [difficulty, puzzle] where puzzle is 81 digits, 0 = empty.\nexport const LEVELS = [\n${body}\n];\n`
);
console.log(`Wrote ${levels.length} levels`);
